services:
  - type: web
    name: picoclaw-bot
    runtime: image
    repo: https://github.com/rahamanleon/Picoclaw-Render-.git
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NVIDIA_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true

  - type: cron
    name: keep-awake
    schedule: "*/5 * * * *"
    command: curl -s -o /dev/null https://picoclaw-bot.onrender.com/health
